# Generated by Django 6.1 on 2026-09-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('buyer_type', models.CharField(choices=[('BUSINESS', 'Business / Buyer'), ('RESTAURANT', 'Restaurant'), ('PROCESSING_UNIT', 'Processing Unit'), ('STORAGE', 'Cold Storage'), ('INPUT_SHOP', 'Agriculture Input Shop'), ('TRANSPORT', 'Transport Provider')], default='BUSINESS', max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('crops_required', models.JSONField(default=list)),
                ('weekly_requirement_kg', models.FloatField(blank=True, null=True)),
                ('offered_price_per_kg', models.FloatField(blank=True, null=True)),
                ('quality_required', models.CharField(default='A', max_length=10)),
                ('contact_mobile', models.CharField(blank=True, max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0.0)),
                ('trust_score', models.FloatField(default=0.0)),
                ('output_products', models.JSONField(default=list, help_text='e.g. ["Ketchup", "Paste"]')),
                ('processing_capacity_kg_day', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', '-trust_score'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(db_index=True, max_length=100)),
                ('market_name', models.CharField(max_length=200)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('min_price_per_kg', models.FloatField()),
                ('max_price_per_kg', models.FloatField()),
                ('modal_price_per_kg', models.FloatField(help_text='Most common / average price')),
                ('arrivals_tonnes', models.FloatField(blank=True, null=True)),
                ('demand_indicator', models.PositiveSmallIntegerField(default=2)),
                ('data_source', models.CharField(default='KRISHAMITRA_MOCK', max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date', 'crop_name'],
                'indexes': [models.Index(fields=['crop_name', 'state', 'date'], name='market_inte_crop_na_86a1ac_idx'), models.Index(fields=['crop_name', 'district', 'date'], name='market_inte_crop_na_3d5fd3_idx')],
            },
        ),
    ]
