# Generated by Django 6.1 on 2026-09-10 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('contact_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('crops_required', models.JSONField(default=list, help_text='List of crop names')),
                ('average_weekly_quantity_kg', models.FloatField(blank=True, null=True)),
                ('quality_preference', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('ANY', 'Any')], default='ANY', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('trust_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('land_size_acres', models.FloatField(blank=True, help_text='Farm size in acres', null=True)),
                ('farming_type', models.CharField(choices=[('ORGANIC', 'Organic'), ('CONVENTIONAL', 'Conventional'), ('MIXED', 'Mixed')], default='CONVENTIONAL', max_length=50)),
                ('years_of_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('trust_score', models.FloatField(default=0.0)),
                ('profile_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Profile',
            },
        ),
    ]
