# Generated by Django 6.1 on 2026-09-10 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Crop name e.g. Tomato, Rice, Cotton', max_length=100)),
                ('variety', models.CharField(blank=True, help_text='Variety/cultivar name', max_length=100)),
                ('quantity_kg', models.FloatField(help_text='Available quantity in kilograms')),
                ('sold_quantity_kg', models.FloatField(default=0)),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A (Premium)'), ('B', 'Grade B (Good)'), ('C', 'Grade C (Processing Grade)')], default='A', max_length=1)),
                ('quality_notes', models.TextField(blank=True)),
                ('sowing_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('expected_price_per_kg', models.FloatField(blank=True, help_text='Farmer expected price', null=True)),
                ('minimum_price_per_kg', models.FloatField(blank=True, null=True)),
                ('images', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PARTIALLY_SOLD', 'Partially Sold'), ('SOLD', 'Sold'), ('PROCESSING', 'Sent to Processing')], default='AVAILABLE', max_length=20)),
                ('disease_analysis', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
